spring:
  application:
    name: apigate

zuul:
  prefix: /api
  routes:
    device-service:
      path: /device/**
      instanceId: http://device-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/